server:
  port: 7001
# spring.application.name 用于指定注册到Eureka Server上的应用名称
spring:
  application:
    name: eureka-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangjf:123@localhost:8761/eureka/
 #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
 #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true
    
turbine:
  app-config: eureka-consumer
  cluster-name-expression: new String("default")
  combine-host-port: true
    
info:
  profile: dev